# Generated by Django 5.1.1 on 2024-10-19 02:12

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidades', '0003_rename_abertura_contabilidade_data_abertura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_etapa', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='AberturaEmpresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_processo', models.CharField(max_length=100, unique=True)),
                ('opcoes_nomes_empresa', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, null=True, size=None)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('endereco', models.CharField(blank=True, max_length=150, null=True)),
                ('telefone', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contabilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidades.contabilidade')),
            ],
        ),
    ]
