# Generated by Django 5.1.1 on 2024-10-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societario', '0002_aberturaempresa_etapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapas',
            name='nome_etapa',
            field=models.CharField(max_length=14),
        ),
    ]
