# Generated by Django 5.1.1 on 2024-10-19 02:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societario', '0003_alter_etapas_nome_etapa'),
    ]

    operations = [
        migrations.CreateModel(
            name='NomeProcessos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_processo', models.CharField(max_length=80)),
            ],
        ),
    ]
