# Generated by Django 5.1.1 on 2024-09-18 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_custom_superuser'),
        ('contabilidades', '0002_alter_contabilidade_nome_fantasia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_custom_superuser',
            new_name='is_admin_contabilidade',
        ),
        migrations.AddField(
            model_name='user',
            name='contabilidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidades.contabilidade'),
        ),
    ]
