# Generated by Django 5.1.1 on 2024-10-17 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_profile_picture'),
        ('contabilidades', '0003_rename_abertura_contabilidade_data_abertura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contabilidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidades.contabilidade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile_pictures'),
        ),
    ]
