# Generated by Django 5.1.1 on 2024-09-18 17:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('abertura', models.DateField()),
                ('situacao', models.CharField(max_length=15)),
                ('tipo', models.CharField(max_length=15)),
                ('nome', models.CharField(max_length=100)),
                ('nome_fantasia', models.CharField(blank=True, max_length=100, null=True)),
                ('porte', models.CharField(max_length=100)),
                ('natureza_juridica', models.CharField(max_length=100)),
                ('cod_atividade_principal', models.CharField(max_length=20)),
                ('desc_atividade_principal', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
