# Generated by Django 5.1.1 on 2024-10-01 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_contabilidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='abertura',
            new_name='data_abertura',
        ),
    ]
