# Generated by Django 5.1.1 on 2024-10-01 19:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_rename_abertura_empresa_data_abertura'),
    ]

    operations = [
        migrations.CreateModel(
            name='AberturaEmpresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_primario', models.CharField(max_length=100)),
                ('nome_secundario', models.CharField(max_length=100)),
                ('nome_terciario', models.CharField(max_length=100)),
                ('atividade_principal', models.CharField(max_length=150)),
                ('responsavel', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='abertura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.aberturaempresa'),
        ),
    ]
