# Generated by Django 5.1.1 on 2024-10-14 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_aberturaempresa_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='abertura',
        ),
        migrations.DeleteModel(
            name='AberturaEmpresa',
        ),
    ]
